// 'use client';

import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
// import { useEffect } from 'react';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // useEffect(() => {
  //   if (typeof window !== 'undefined' && window.Telegram) {
  //     console.log('script loaded correctly, window.Telegram has been populated');
  //     console.log(window.Telegram.WebApp)
  //     console.log("***")
  //     console.log(window.Telegram.WebApp.initData)

  //   }
  // }, []);

  return (
    <html lang="en">
      <head>
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="beforeInteractive"
          // onLoad={() => {
          //   console.log('Script loaded and executed');
          // }}
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
