//'use client'
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './page.module.css';
import Script from 'next/script';
import "bootstrap/dist/css/bootstrap.min.css";
import './10015.css'

import Nav from './_components/Nav'


import { UserProvider } from "./context/userContext";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'RMPA - Rate My Professor AASTU',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" suppressHydrationWarning >
      <head>
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className={`${inter.className} container `}>

        <Nav />
        <UserProvider>{children}</UserProvider>

      </body>
    </html>
  );
}
